#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -sname reltool
main(_) ->
  {ok, Conf} = file:consult("release/cells.config"),
  {ok, Spec} = reltool:get_target_spec(Conf),
  reltool:eval_target_spec(Spec, code:root_dir(), "rel").
